"use client";
import {AuthEntry} from "./auth-ui";
import {useEffect,useState} from 'react';
import {useLanguage,LanguageProvider,LanguageSwitcher} from './i18n/provider';
import type {Locale} from './i18n/shared';
import './compliance.css';
export function PublicShell({locale,children}:{locale:Locale;children:React.ReactNode}){return <LanguageProvider initialLocale={locale}><main className="legal-shell"><header className="legal-header"><a href="/" className="brand">Gigs</a><LanguageSwitcher/></header>{children}</main><LegalFooter/></LanguageProvider>;}
export function LegalFooter(){const {t}=useLanguage();const [open,setOpen]=useState(false);
 useEffect(()=>{setOpen(!document.cookie.split('; ').some(v=>v==='shabashka_cookie_notice=v1'));},[]);
 function close(){document.cookie=`shabashka_cookie_notice=v1; Path=/; Max-Age=15552000; SameSite=Lax${location.protocol==='https:'?'; Secure':''}`;setOpen(false);}
 return <><nav className="legal-footer" aria-label={t('Правовая информация')}><a href="/legal/terms">{t('Условия использования')}</a><a href="/legal/privacy">{t('Конфиденциальность')}</a><a href="/legal/cookies">{t('Cookie')}</a><button onClick={()=>setOpen(true)}>{t('Настройки cookie')}</button><a href="/privacy">{t('Мои данные')}</a><a href="mailto:igors.nikos@gmail.com">{t('Связаться с оператором')}</a></nav>{open&&<aside className="cookie-notice" aria-label={t('Cookie')}><div><strong>{t('Только необходимые cookie')}</strong><p>{t('Мы используем cookie для входа, выбранного языка и сохранения этого уведомления. Аналитика и рекламные cookie не подключены.')}</p></div><a href="/legal/cookies">{t('Подробнее')}</a><button className="dark" onClick={close}>{t('Понятно')}</button></aside>}</>;
}
export function ReportLink({id}:{id:string}){const{t}=useLanguage();return <a className="report-link" href={'/report?target='+encodeURIComponent(id)}>{t('Пожаловаться / незаконный контент')}</a>;}
export function PrivacyPanel(){
 const{t,errorText,locale}=useLanguage();const[state,setState]=useState<{inactive?:boolean;erased?:boolean}|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(''),[showErase,setShowErase]=useState(false),[guest,setGuest]=useState(false),[notice,setNotice]=useState('');
 async function load(){try{const r=await fetch('/api/privacy',{cache:'no-store',headers:{'X-SHABASHKA-Language':locale}});if(r.status===401){setGuest(true);return;}const b=await r.json() as {state:typeof state;errorKey?:string};if(!r.ok)throw Error(b.errorKey);setState(b.state);}catch(e){setError(e instanceof Error?e.message:'Не удалось загрузить данные. Попробуйте ещё раз.');}finally{setLoading(false);}}
 useEffect(()=>{load();},[locale]);
 async function change(action:string){setBusy(true);setError('');try{const r=await fetch('/api/privacy',{method:'POST',headers:{'Content-Type':'application/json','X-SHABASHKA-Language':locale},body:JSON.stringify({action,confirm})});const b=await r.json() as {errorKey?:string};if(!r.ok)throw Error(b.errorKey);setNotice(action==='erase'?'Данные аккаунта удалены.':'Сохранено.');setShowErase(false);await load();}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить.');}finally{setBusy(false);}}
 return <><p className="legal-kicker">Gigs · {t('Конфиденциальность')}</p><h1>{t('Мои данные')}</h1><p>{t('Управляйте данными своего аккаунта. Удаление не затрагивает ваш аккаунт ChatGPT.')}</p>{error&&<p role="alert" className="compliance-error">{errorText(error)}</p>}{notice&&<p role="status">{t(notice)}</p>}{loading?<p>{t('Загрузка…')}</p>:guest?<AuthEntry/>:<>
 <section className="privacy-card"><h2>{t('Экспорт данных')}</h2><p>{t('Скачайте JSON: профиль, задания, отклики, доступную переписку, отзывы и ваши обращения. Файл содержит персональные данные — храните его безопасно.')}</p><a className="outline" href="/api/privacy?export=1" download>{t('Скачать мои данные')}</a></section>
 {!state?.erased&&<section className="privacy-card"><h2>{state?.inactive?t('Аккаунт деактивирован'):t('Деактивация аккаунта')}</h2><p>{t('Публикации скрываются, новые действия недоступны. Данные сохраняются; аккаунт можно активировать снова.')}</p><button className="outline" disabled={busy||!state} onClick={()=>change(state?.inactive?'reactivate':'deactivate')}>{state?.inactive?t('Активировать аккаунт'):t('Деактивировать аккаунт')}</button></section>}
 <section className="privacy-card danger"><h2>{t('Удалить аккаунт и данные')}</h2>{state?.erased?<><p>{t('Данные аккаунта удалены.')}</p><a href="/">{t('На главную')}</a></>:<><p>{t('Будут удалены профиль, публикации, отзывы, обращения и связанные диалоги, включая сообщения собеседников. Восстановление невозможно. Сначала скачайте экспорт.')}</p><p>{t('Сохранится только техническая отметка удаления без имени и контактов, чтобы открытая сессия не восстановила данные. Копии у собеседников и резервные копии хостинга требуют отдельного обращения к оператору.')}</p>{showErase?<div><label>{t('Введите DELETE для подтверждения удаления.')}<input value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="off"/></label><div className="compliance-actions"><button className="outline" disabled={busy} onClick={()=>setShowErase(false)}>{t('Отмена')}</button><button className="dark" disabled={busy||confirm!=='DELETE'} onClick={()=>change('erase')}>{t('Удалить без восстановления')}</button></div></div>:<button className="outline" disabled={busy} onClick={()=>setShowErase(true)}>{t('Удалить аккаунт и данные')}</button>}</>}</section>
 </>}<p>{t('Исправление, ограничение обработки, возражения и вопросы о данных:')} <a href="mailto:igors.nikos@gmail.com">igors.nikos@gmail.com</a></p></>;
}
export function ReportPanel({target}:{target:string}){
 const{t,locale,errorText}=useLanguage();const[category,setCategory]=useState('illegal'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState('');
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const values=Object.fromEntries(new FormData(e.currentTarget));try{const r=await fetch('/api/reports',{method:'POST',headers:{'Content-Type':'application/json','X-SHABASHKA-Language':locale},body:JSON.stringify({...values,target,category,goodFaith:values.goodFaith==='on'})});const b=await r.json() as {id:string;token:string;errorKey:string};if(!r.ok)throw Error(b.errorKey);setReceipt('/report/status?id='+encodeURIComponent(b.id)+'#'+b.token);}catch(e){setError(e instanceof Error?e.message:'Не удалось сохранить.');}finally{setBusy(false);}}
 return <><h1>{t('Сообщить о нарушении')}</h1><p>{t('Регистрация не требуется. Опишите, какой контент нарушает закон или правила и почему. Не прикладывайте незаконные материалы.')}</p>{receipt?<section className="privacy-card" role="status"><h2>{t('Обращение получено')}</h2><p>{t('Сохраните закрытую ссылку: по ней доступны статус и решение. Не передавайте её другим. Уведомления по email отправляет оператор вручную.')}</p><a className="dark" href={receipt}>{t('Открыть статус обращения')}</a></section>:<form className="compliance-form" onSubmit={submit}><p><a href={'/?item='+encodeURIComponent(target)} target="_blank" rel="noreferrer">{t('Публикация')} ↗</a></p><label>{t('Причина')}<select value={category} onChange={e=>setCategory(e.target.value)}><option value="illegal">{t('Предположительно незаконный контент')}</option><option value="rules">{t('Нарушение правил площадки')}</option><option value="child-safety">{t('Сексуальная эксплуатация детей')}</option></select></label><label>{t('Подробное обоснование')}<textarea name="reason" required minLength={20} maxLength={4000} rows={6}/></label><label>{t('Ваше имя')}<input name="name" required={category!=='child-safety'} maxLength={100}/></label><label>Email<input name="email" type="email" required={category!=='child-safety'} maxLength={254}/></label>{category==='child-safety'&&<p>{t('Для этой категории имя и email необязательны.')}</p>}<label className="check-label"><input name="goodFaith" type="checkbox" required/>{t('Добросовестно считаю сведения в обращении точными и полными.')}</label><p>{t('Контакты заявителя доступны только оператору. Обработка обращения описана в политике конфиденциальности.')} <a href="/legal/privacy">{t('Конфиденциальность')}</a></p>{error&&<p role="alert" className="compliance-error">{errorText(error)}</p>}<button className="dark" disabled={busy||!target}>{busy?t('Сохранение…'):t('Отправить обращение')}</button></form>}</>;
}
export function ReportStatus(){const{t,locale,errorText}=useLanguage();const[data,setData]=useState<{id:string;status:string;decision?:string;basis?:string;created:string}|null>(null),[error,setError]=useState('');async function load(){try{const id=new URLSearchParams(location.search).get('id')||'',token=location.hash.slice(1);const r=await fetch('/api/reports?id='+encodeURIComponent(id),{headers:{'X-Report-Token':token,'X-SHABASHKA-Language':locale},cache:'no-store'});const b=await r.json() as NonNullable<typeof data>&{errorKey:string};if(!r.ok)throw Error(b.errorKey);setData(b);setError('');}catch(e){setError(e instanceof Error?e.message:'Обращение не найдено.');}}useEffect(()=>{load();},[locale]);return <><h1>{t('Статус обращения')}</h1>{error?<p role="alert">{errorText(error)}</p>:data?<section className="privacy-card"><p>{t('Номер обращения')}: {data.id}</p><h2>{t(data.status==='pending'?'На рассмотрении':data.status==='removed'?'Публикация скрыта':'Ограничение не применено')}</h2>{data.decision&&<><p className="preserve-text">{data.decision}</p><p>{t('Основание')}: {data.basis}</p><p>{t('Решение принято человеком. Если вы не согласны, отправьте оператору номер обращения и обоснование пересмотра.')}</p><a href="mailto:igors.nikos@gmail.com">igors.nikos@gmail.com</a></>}</section>:<p>{t('Загрузка…')}</p>}<button className="outline" onClick={load}>{t('Обновить')}</button></>;}
