import assert from 'node:assert/strict';
const origin=process.env.TEST_ORIGIN||'http://127.0.0.1:5174';
if(!['127.0.0.1','localhost'].includes(new URL(origin).hostname))throw Error('Local Worker only');
const prefix='admin-test-'+Date.now();
const admin={id:prefix+'-admin',email:process.env.TEST_ADMIN_EMAIL||'seedy@sites.test'};
const customer={id:prefix+'-customer',email:'customer@example.test'},provider={id:prefix+'-provider',email:'provider@example.test'};
let checks=0;
async function req(path,user,body,status=200,extra={}){
 const headers={Connection:'close',...(user?{'oai-authenticated-user-id':user.id,'oai-authenticated-user-email':user.email}:{}),...(body?{Origin:origin,'Content-Type':'application/json'}:{}),...extra};
 const r=await fetch(origin+path,{method:body?'POST':'GET',headers,body:body?JSON.stringify(body):undefined});
 const result=await r.json();assert.equal(r.status,status,JSON.stringify(result));checks++;return result;
}
const market=(u,b,s)=>req('/api/market',u,b,s),manage=(b,s)=>req('/api/admin',admin,b,s);
await req('/api/admin',null,undefined,401);
await req('/api/admin',customer,undefined,403);
await req('/api/admin',customer,{action:'restore',id:'anything',reason:'test'},403);
await req('/api/admin',null,{action:'restore'},401);
await req('/api/admin',admin,{action:'restore'},403,{Origin:'https://unrelated.example'});
await req('/api/admin?kind=message',admin,undefined,400);
await req('/api/admin?page=1.5',admin,undefined,400);
await market(admin,{action:'register',name:prefix+' админ',role:'customer'});
await market(customer,{action:'register',name:prefix+' заказчик',role:'customer',isAdmin:true});
await market(provider,{action:'register',name:prefix+' исполнитель',role:'provider'});
assert.equal((await market(customer)).user.isAdmin,false);checks++;
assert.equal((await market(admin)).user.isAdmin,true);checks++;
await manage({action:'restrict',id:'account:'+admin.id,reason:'self block'},400);
await manage({action:'restrict',id:'missing',reason:'not found'},404);
await manage({action:'restrict',id:'account:'+customer.id,reason:''},400);
const common={title:prefix,description:'Проверка админки',category:'Ремонт',city:'Рига',price:'50 €'};
await market(provider,{action:'profile',...common,skills:'Сборка'});
const task=await market(customer,{action:'task',...common});
await market(provider,{action:'bid',parent:task.id,description:'Готов',price:'40 €'});
const bid=(await market(customer)).records.find(r=>r.kind==='bid'&&r.parent===task.id);
const restrict=id=>manage({action:'restrict',id,reason:'Тестовое ограничение'});
const restore=id=>manage({action:'restore',id,reason:'Проверка восстановления'});
await restrict(task.id);
assert.ok(!(await market(null)).records.some(r=>r.id===task.id));checks++;
await market(provider,{action:'bid',parent:task.id,description:'Готов',price:'40 €'},403);
await market(customer,{action:'choose',id:bid.id},403);
await market(provider,{action:'message',parent:bid.id,description:'Нельзя'},403);
let list=await req('/api/admin?kind=task&q='+prefix,admin);
assert.ok(list.rows.find(r=>r.id===task.id)?.restricted);checks++;
await restore(task.id);
assert.ok((await market(null)).records.some(r=>r.id===task.id));checks++;
await restrict('profile:'+provider.id);
await market(provider,{action:'profile',...common,skills:'Изменённые навыки'});
assert.ok(!(await market(null)).records.some(r=>r.id==='profile:'+provider.id));checks++;
await restore('profile:'+provider.id);
await restrict('account:'+provider.id);
assert.ok((await market(provider)).user.blocked);checks++;
assert.ok(!(await market(null)).records.some(r=>r.id==='profile:'+provider.id));checks++;
await market(provider,{action:'register',name:'Другая роль',role:'customer'},403);
await market(provider,{action:'message',parent:bid.id,description:'Нельзя'},403);
await market(provider,{action:'profile',...common,skills:'Нельзя'},403);
await market(customer,{action:'choose',id:bid.id},403);
await restore('account:'+provider.id);
await market(customer,{action:'choose',id:bid.id});
await market(customer,{action:'complete',id:task.id});
await market(customer,{action:'review',parent:task.id,rating:5,description:'Хорошо'});
await restrict('review:'+task.id);
assert.ok(!(await market(null)).records.some(r=>r.id==='review:'+task.id));checks++;
await restore('review:'+task.id);
assert.ok((await market(null)).records.some(r=>r.id==='review:'+task.id));checks++;
await restrict('account:'+customer.id);
assert.ok(!(await market(null)).records.some(r=>r.id===task.id));checks++;
await restore('account:'+customer.id);
const audit=await req('/api/admin?kind=audit&q='+prefix,admin);
assert.equal(audit.total,10);checks++;
assert.ok(audit.rows.every(r=>r.reason&&r.actor===admin.email));checks++;
const publicData=await market(admin);
assert.ok(!publicData.records.some(r=>['audit','block','hidden','account'].includes(r.kind)));checks++;
const page2=await req('/api/admin?kind=account&q='+prefix+'&page=2',admin);
assert.equal(page2.rows.length,0);checks++;
console.log(JSON.stringify({passed:checks,testOwnerPrefix:prefix}));
